// <auto-generated />
namespace Lottery.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class addsequencedata : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addsequencedata));
        
        string IMigrationMetadata.Id
        {
            get { return "202009161442499_add sequence data"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
